### ISSUE TITLE
sessionify and apollo

### ISSUE THREAD

**Issue by jkao1** [stuyspec/client-app#93]
The RoutingApp on `feature/apollo` should be able to get a user session from not only the `localStorage` but also URL query strings (from user confirmation links).

**Comment by NicholasLYang** [comment]
Also rename sessionfy. Terrible name

**Comment by jkao1** [comment]
Actually it's sesssionIFY.

**Comment by NicholasLYang** [comment]
Not in the code it ain't

**Comment by jkao1** [comment]
Yes in `feature/apollo`.

**Comment by NicholasLYang** [comment]
Just make it createSession
